spring.application.name=MessageApp

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=${messengerdb.username}
spring.datasource.password=${messengerdb.password}

spring.cloud.vault.token=00000000-0000-0000-0000-000000000000
spring.cloud.vault.scheme=http
spring.cloud.vault.kv.enabled=true
spring.config.import=vault://

logging.level.sql = debug
logging.level.web = debug
logging.level.org.springframework.security = debug

dev.camp.security.environment = dev

spring.web.error.include-stacktrace = always
spring.web.error.include-message = always
spring.jps.show-sql = true

spring.h2.console.path = /h2c


# encryption password, default = password, for now
app.key.password=${KEY_PASSWORD:password}